// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SparkTrack.DataAccess.EFCore;

#nullable disable

namespace SparkTrack.DataAccess.EFCore.Migrations
{
    [DbContext(typeof(SparkTrackDbContext))]
    [Migration("20260228113540_SubTasksRelations")]
    partial class SubTasksRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeatureDataUserData", b =>
                {
                    b.Property<Guid>("AuthorsListId")
                        .HasColumnType("uuid");

                    b.Property<int>("FeaturesListId")
                        .HasColumnType("integer");

                    b.HasKey("AuthorsListId", "FeaturesListId");

                    b.HasIndex("FeaturesListId");

                    b.ToTable("FeatureDataUserData");
                });

            modelBuilder.Entity("SparkTrack.Authentication.DataAccess.EFCore.Data.RefreshTokenData<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.AttachmentData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Checksum")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("CommentDataId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FeatureDataId")
                        .HasColumnType("integer");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsImage")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommentDataId");

                    b.HasIndex("FeatureDataId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.BonusPaymentData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<float>("Payment")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Bonuses");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.CommentData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.FeatureData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveSource")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.PaymentData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Payment")
                        .HasColumnType("real");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("TaskId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.ProjectData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ArchiveSource")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.SubTaskData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExecutorEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTimelyBonusApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<float>("TimelyBonus")
                        .HasColumnType("real");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExecutorEmployeeId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("IsCompleted");

                    b.ToTable("SubTasks");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ArchiveSource")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelegramTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TelegramTag")
                        .IsUnique()
                        .HasFilter("\"TelegramTag\" IS NOT NULL AND \"TelegramTag\" != ''");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SubTaskDataSubTaskData", b =>
                {
                    b.Property<Guid>("DependentForListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependsOnListId")
                        .HasColumnType("uuid");

                    b.HasKey("DependentForListId", "DependsOnListId");

                    b.HasIndex("DependsOnListId");

                    b.ToTable("SubTaskDataSubTaskData");
                });

            modelBuilder.Entity("FeatureDataUserData", b =>
                {
                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.UserData", null)
                        .WithMany()
                        .HasForeignKey("AuthorsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.FeatureData", null)
                        .WithMany()
                        .HasForeignKey("FeaturesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.AttachmentData", b =>
                {
                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.CommentData", null)
                        .WithMany("AttachmentsList")
                        .HasForeignKey("CommentDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.FeatureData", null)
                        .WithMany("AttachmentsList")
                        .HasForeignKey("FeatureDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.BonusPaymentData", b =>
                {
                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.UserData", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.UserData", "Employee")
                        .WithMany("Bonuses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.CommentData", b =>
                {
                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.FeatureData", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.FeatureData", b =>
                {
                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.ProjectData", "Project")
                        .WithMany("Features")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.PaymentData", b =>
                {
                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.UserData", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.SubTaskData", "Task")
                        .WithMany("Payments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.SubTaskData", b =>
                {
                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.UserData", "ExecutorEmployee")
                        .WithMany()
                        .HasForeignKey("ExecutorEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.FeatureData", "Feature")
                        .WithMany("TasksList")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutorEmployee");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("SubTaskDataSubTaskData", b =>
                {
                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.SubTaskData", null)
                        .WithMany()
                        .HasForeignKey("DependentForListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SparkTrack.DataAccess.EFCore.Data.Entities.SubTaskData", null)
                        .WithMany()
                        .HasForeignKey("DependsOnListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.CommentData", b =>
                {
                    b.Navigation("AttachmentsList");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.FeatureData", b =>
                {
                    b.Navigation("AttachmentsList");

                    b.Navigation("TasksList");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.ProjectData", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.SubTaskData", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SparkTrack.DataAccess.EFCore.Data.Entities.UserData", b =>
                {
                    b.Navigation("Bonuses");
                });
#pragma warning restore 612, 618
        }
    }
}
