<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fanatiki.Loading\Fanatiki.Loading.csproj" />
      <ProjectReference Include="..\SparkTrack.Core.Shared\SparkTrack.Core.Shared.csproj" />
      <ProjectReference Include="..\SparkTrack.Reactive\SparkTrack.Reactive.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" />
      <PackageReference Include="NLog" />
    </ItemGroup>

</Project>
