<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
  
    <ItemGroup>
      <PackageReference Include="Autofac.Extensions.DependencyInjection" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="NSwag.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SparkTrack.Core.Shared\SparkTrack.Core.Shared.csproj" />
      <ProjectReference Include="..\SparkTrack.Core\SparkTrack.Core.csproj" />
      <ProjectReference Include="..\SparkTrack.DataAccess.EFCore\SparkTrack.DataAccess.EFCore.csproj" />
    </ItemGroup>

</Project>
