<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SparkTrack.Authentication.Core\SparkTrack.Authentication.Core.csproj" />
    </ItemGroup>

</Project>
