<Project>
    <!--Настройки проектов-->
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublisherName>Fanatiki</PublisherName>
        <Version>0.0.0.5</Version>
    </PropertyGroup>
</Project>