<Project>
    <!--Настройки проектов-->
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <Version>0.5.1.0</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
        <PublisherName>Fanatiki</PublisherName>
        <Copyright>v$(Version) © $(PublisherName)</Copyright>
    </PropertyGroup>
</Project>