<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Controls.DataGrid" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" >
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Avalonia.ReactiveUI" />
        <PackageReference Include="FluentAvaloniaUI" />
        <PackageReference Include="FluentIcons.Avalonia.Fluent" />
        <PackageReference Include="NLog" />
        <PackageReference Include="ReactiveUI.Fody" />
        <PackageReference Include="Xaml.Behaviors" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Windows\Main\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fanatiki.MVVM\Fanatiki.MVVM.csproj" />
      <ProjectReference Include="..\SparkTrack.Core.Client\SparkTrack.Core.Client.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controls\" />
    </ItemGroup>
</Project>
