; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SparkTrack"
#ifndef MyMajor
#define MyMajor 1
#endif
#ifndef MyMinor
#define MyMinor 1
#endif
#ifndef MyBuild
#define MyBuild 1
#endif
#ifndef MyRevision
#define MyRevision 1
#endif
#define MyAppVersion Str(MyMajor) + "." + Str(MyMinor) + "." + Str(MyBuild)  + "." + Str(MyRevision)
#define MyAppPublisher "Fanatiki"
#define MyAppExeName "SparkTrack.Desktop.exe"
#define MyFiles "./FilesForCompile"
#define MyDefaultGroupName "Fanatiki"
#define MyAppRegKey "SparkTrack"


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A78D6979-8806-49F5-832F-223C7C5EBC8E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyDefaultGroupName}
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=admin
OutputBaseFilename=install-{#MyAppName}-{#MyAppVersion}
Compression=zip
SolidCompression=yes
WizardStyle=modern
SetupIconFile={#MyFiles}\icon.ico


[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"


[Files]
Source: {#MyFiles}\*; DestDir: {app}; Flags: ignoreversion recursesubdirs createallsubdirs;


[Registry]
// Versioning stuff
Root: HKLM; Subkey: "Software\{#MyAppPublisher}"; Flags: uninsdeletekeyifempty
Root: HKLM; Subkey: "Software\{#MyAppPublisher}\{#MyAppRegKey}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\{#MyAppPublisher}\{#MyAppRegKey}\Version"; ValueType: string; ValueName: "Major"; ValueData: "{#MyMajor}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\{#MyAppPublisher}\{#MyAppRegKey}\Version"; ValueType: string; ValueName: "Minor"; ValueData: "{#MyMinor}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\{#MyAppPublisher}\{#MyAppRegKey}\Version"; ValueType: string; ValueName: "Build"; ValueData: "{#MyBuild}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\{#MyAppPublisher}\{#MyAppRegKey}\Version"; ValueType: string; ValueName: "Revision"; ValueData: "{#MyRevision}"; Flags: uninsdeletekey

// Deep link stuff
Root: HKCR; Subkey: "sparktrack"; ValueType: string; ValueData: "URL:SparkTrack Protocol"; Flags: uninsdeletekey
Root: HKCR; Subkey: "sparktrack"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKCR; Subkey: "sparktrack\DefaultIcon"; ValueType: string; ValueData: "{app}\icon.ico"
Root: HKCR; Subkey: "sparktrack\shell\open\command"; \
    ValueType: string; \
    ValueData: """{app}\{#MyAppExeName}"" ""%1"""

    
[Icons]
Name: {group}\{#MyAppName}; WorkingDir: {app}; Filename: {app}\{#MyAppExeName}; IconFilename: {app}\icon.ico
Name: {group}\{cm:UninstallProgram,{#MyAppName}}; Filename: "{uninstallexe}"
Name: {userdesktop}\{#MyAppName}; Filename: {app}\{#MyAppExeName}; WorkingDir: {app}; IconFilename: {app}\icon.ico


[UninstallDelete]
Type: files; Name: "{userdesktop}\{#MyAppName}.lnk"
Type: files; Name: "{commondesktop}\{#MyAppName}.lnk"


[Run]
Filename: {app}\{#MyAppExeName}; \
    Description: {cm:LaunchProgram,{#MyAppName}}; \
    Flags: nowait postinstall; \
    Check: ShouldLaunch;
Filename: {app}\clear-temp-installer.bat; \
    Parameters: "{srcexe}"; \
    Flags: runhidden nowait postinstall; \
    Check: ShouldClearInstallerAfterInstall;

    
[Code]

function ShouldLaunch: Boolean;
begin
  Result := False;
  if ExpandConstant('{param:AUTORUN|0}') = '1' then
  begin
    Result := True;
  end;
end;

function ShouldClearInstallerAfterInstall: Boolean;
begin
  Result := False;
  if ExpandConstant('{param:AUTOREMOVE|0}') = '1' then
  begin
    Result := True;
  end;
end;