<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SparkTrack.Authentication.DataAccess.EFCore\SparkTrack.Authentication.DataAccess.EFCore.csproj" />
      <ProjectReference Include="..\SparkTrack.Core.Shared\SparkTrack.Core.Shared.csproj" />
      <ProjectReference Include="..\SparkTrack.Core\SparkTrack.Core.csproj" />
    </ItemGroup>

</Project>
